language: node_js

node_js:
  - 0.8

before_install:
  - sudo sh -c "echo 'JVM_OPTS=\"$JVM_OPTS -Djava.net.preferIPv4Stack=false\"' >> /usr/local/cassandra/conf/cassandra-env.sh"
  - sudo service cassandra start
  - sudo service cassandra status
  - sleep 5

script:
  - npm run-script lint
  - npm run-script test

notifications:
  email:
    - tomaz+travisci@tomaz.me
