#!/bin/bash
#
# Copyright 2013 Rackspace
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# args:
# 1 (required) : config directory (may contain log4j and zoo.cfg).
# 2 (required) : tmp dir for pid file, log, etc.

ZOOCFGDIR=$1
ZOOCFG="$ZOOCFGDIR/zoo.cfg"
ZOOKEEPER_VERSION="3.4.5"

if [ $TRAVIS ]; then
  ZOODIR="tests/deps/zookeeper-20120116174103"
  JVMFLAGS="-XX:MaxPermSize=256M -Xms128M -Xmx256M"

  rm -rf $ZOODIR
  tar -xzvf tests/deps/zookeeper-20120116174103.tar.gz -C tests/deps/
else
  ZOODIR="/opt/zookeeper"
fi

CLASSPATH="$ZOOCFGDIR:$ZOODIR/build/classes:$ZOODIR/build/lib/slf4j-log4j12-1.6.1.jar:$ZOODIR/build/lib/slf4j-api-1.6.1.jar:$ZOODIR/bin/../build/lib/netty-3.2.2.Final.jar:$ZOODIR/bin/../build/lib/log4j-1.2.15.jar:$ZOODIR/build/lib/jline-0.9.94.jar:$ZOODIR/lib/*.jar:$ZOODIR/zookeeper-*.jar:$ZOODIR/src/java/lib/ivy-2.2.0.jar"

JAVA=/usr/bin/java
ZOOMAIN="org.apache.zookeeper.server.quorum.QuorumPeerMain"
ZOO_LOG4J_PROP="DEBUG,CONSOLE"
JMXLOCALONLY=false
JAVA_OPTS=""

# Only follow symlinks if readlink supports it
if readlink -f "$0" > /dev/null 2>&1
then
  ZOOBIN=`readlink -f "$0"`
else
  ZOOBIN="$0"
fi

echo "Using config: $ZOOCFG"

rm -rf /tmp/zk/data
mkdir -p /tmp/zk/data

echo  "Starting zookeeper ... "
exec java  "-Dzookeeper.root.logger=${ZOO_LOG4J_PROP}" \
    -cp "$CLASSPATH" $JVMFLAGS $ZOOMAIN "$ZOOCFG"
